//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInquiryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Customer
    {
        public Master_Customer()
        {
            this.Process_Transaction = new HashSet<Process_Transaction>();
        }
    
        public decimal CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
    
        public virtual ICollection<Process_Transaction> Process_Transaction { get; set; }
    }
}
