//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInquiryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Transaction
    {
        public decimal TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CustomerId { get; set; }
    
        public virtual Master_Customer Master_Customer { get; set; }
    }
}
